# docker-compose.yml


version: "3.2"
services:
    rabbitmq:
        image: "rabbitmq:management-alpine"
        logging:
            driver: none
        ports:
            - "8081:15672"
    
    python-app:
        build: ./python-app
        depends_on:
            - rabbitmq
        volumes:
            - type: bind
              source: ./python-app
              target: /usr/src/app
        tty: true
